// Code generated by "stringer -type EtherType -linecomment"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProtoIP-2048]
	_ = x[ProtoARP-2054]
	_ = x[ProtoRARP-2101]
}

const (
	_EtherType_name_0 = "ip"
	_EtherType_name_1 = "arp"
	_EtherType_name_2 = "rarp"
)

func (i EtherType) String() string {
	switch {
	case i == 2048:
		return _EtherType_name_0
	case i == 2054:
		return _EtherType_name_1
	case i == 2101:
		return _EtherType_name_2
	default:
		return "EtherType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
