// Code generated by "stringer -type TransProto -linecomment"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TCP-6]
	_ = x[UDP-17]
}

const (
	_TransProto_name_0 = "tcp"
	_TransProto_name_1 = "udp"
)

func (i TransProto) String() string {
	switch {
	case i == 6:
		return _TransProto_name_0
	case i == 17:
		return _TransProto_name_1
	default:
		return "TransProto(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
